### ISSUE TITLE
遇到某种特殊弹幕后导致xml转ass不完全

### ISSUE THREAD

**Issue by GPY1999** [gwy15/danmu2ass#14]
正常的抓到的弹幕是这个形式：
```   <d p="2814.009,1,25,65532,1701171728450,0,22146432,0" user="潘柒颂PanChihSong">对三，要不起</d>```

但是最近录到的弹幕里偶尔会出现这种弹幕，我怀疑是b站新出的弹幕复读功能：
```<d p="2814.062,7,100,16777215,1701171730079,0,0,0" user="***">[1.0,0.0,"0.8-0.5",10.0,"对三，要不起",0.0,0.0,0.0,0.0,10000,0,true,"黑体",1]</d>```

如果存在这种弹幕，他后面的所有弹幕都不能转化成ass文件，我尝试阅读了这个软件的源代码但是没读懂，所以请问这个问题该如何解决呢？

如果我通过加denylist的方式解决，我在denylist里加一个`[`能把这些弹幕排除掉吗？谢谢！

**Comment by GPY1999** [comment]
更新：我发现danmu2ass在转这种形式的弹幕时报错是：

```Caused by:
    未知的弹幕类型：7
```

**Comment by GPY1999** [comment]
我想我大概明白了，问题出在弹幕类型上，之前正常的都是1，即正常的滚动，但是这个新弹幕的是7，现在的软件没有识别这个的功能

**Comment by gwy15** [comment]
晚上支持一下吧，可以提供下这个 xml 吗

**Comment by GPY1999** [comment]
[录制-948391-20231128-185512-906-一周军情观察：废墟之中的作战.zip](https://github.com/gwy15/danmu2ass/files/13520048/-948391-20231128-185512-906-.zip)

这个压缩包里有xml，打开之后搜索黑体就能找到对应的弹幕。

谢谢！

**Comment by gwy15** [comment]
close via 1966a82
